# Generated by Django 3.1.1 on 2020-09-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=400)),
                ('pkey', models.PositiveSmallIntegerField(blank=True, help_text='Unique Product Key or Catalogue number. Current P.Key is unique', max_length=100, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(help_text='Initial quantity value. Do no try to create a produt that already exists.')),
                ('price', models.DecimalField(decimal_places=2, help_text=' ex: $ 127.99 * Just type numbers', max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.category')),
            ],
        ),
        migrations.CreateModel(
            name='HistConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.PositiveSmallIntegerField()),
                ('transition', models.IntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('user', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
    ]
