# Generated by Django 3.1.1 on 2020-09-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200907_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pkey',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Unique Product Key or Catalogue number. Current P.Key is unique', unique=True),
        ),
    ]
