# Generated by Django 3.1.1 on 2022-09-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200907_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pkey',
            field=models.PositiveSmallIntegerField(blank=True, help_text='DONT TOUCH!!!! Unique Product Key or Catalogue number. Current P.Key is unique', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text=' ex: $ 127.99 * to TWO Decimal Places', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='Initial quantity value. Do no try to create a produt that already exists!'),
        ),
    ]
